Circle = require("./elements/Circle")
Rectangle = require("./elements/Rectangle")
DataCircle = require('./data/circles')

class App extends PIXI.Application
  animation:true
  animationNodes:[]
  constructor:(w,h,o)->
    super(w,h,o)
    @renderer.resize(window.innerWidth, window.innerHeight)
    document.body.appendChild @view
    document.body.style.margin= 0
    @build()
    @animate()

  build:=>
   
    rectangle1= new Rectangle(0x00fff,0,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle1)
    @addAnimationNodes(rectangle1)
    rectangle2= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle2)
    @addAnimationNodes(rectangle2)
    rectangle3= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle3)
    @addAnimationNodes(rectangle3)
    rectangle4= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle4)
    @addAnimationNodes(rectangle4)
    rectangle5= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle5)
    @addAnimationNodes(rectangle5)
    rectangle6= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle6)
    @addAnimationNodes(rectangle6)
    rectangle7= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle7)
    @addAnimationNodes(rectangle7)
    rectangle8= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,0,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle8)
    @addAnimationNodes(rectangle8)

    
    console.log window.innerHeight/8
    rectangle9= new Rectangle(0x00fff,0,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle9)
    @addAnimationNodes(rectangle9)
    rectangle10= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle10)
    @addAnimationNodes(rectangle10)
    rectangle11= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle11)
    @addAnimationNodes(rectangle11)
    rectangle12= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle12)
    @addAnimationNodes(rectangle12)
    rectangle13= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle13)
    @addAnimationNodes(rectangle13)
    rectangle14= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle14)
    @addAnimationNodes(rectangle14)
    rectangle15= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle15)
    @addAnimationNodes(rectangle15)
    rectangle16= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle1.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle16)
    @addAnimationNodes(rectangle16)
    

    rectangle17= new Rectangle(0x00fff,0,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle17)
    @addAnimationNodes(rectangle17)
    rectangle18= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle18)
    @addAnimationNodes(rectangle18)
    rectangle19= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle19)
    @addAnimationNodes(rectangle19)
    rectangle20= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle20)
    @addAnimationNodes(rectangle20)
    rectangle21= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle21)
    @addAnimationNodes(rectangle21)
    rectangle22= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle22)
    @addAnimationNodes(rectangle22)
    rectangle23= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle23)
    @addAnimationNodes(rectangle23)
    rectangle24= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle16.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle24)
    @addAnimationNodes(rectangle24)


    rectangle25= new Rectangle(0x00fff,0,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle25)
    @addAnimationNodes(rectangle25)
    rectangle26= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle26)
    @addAnimationNodes(rectangle26)
    rectangle27= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle27)
    @addAnimationNodes(rectangle27)
    rectangle28= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle28)
    @addAnimationNodes(rectangle28)
    rectangle29= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle29)
    @addAnimationNodes(rectangle29)
    rectangle30= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle30)
    @addAnimationNodes(rectangle30)
    rectangle31= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle31)
    @addAnimationNodes(rectangle31)
    rectangle32= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle24.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle32)
    @addAnimationNodes(rectangle32)
    

    rectangle33= new Rectangle(0x00fff,0,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle33)
    @addAnimationNodes(rectangle33)
    rectangle34= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle34)
    @addAnimationNodes(rectangle34)
    rectangle35= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle35)
    @addAnimationNodes(rectangle35)
    rectangle36= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle36)
    @addAnimationNodes(rectangle36)
    rectangle37= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle37)
    @addAnimationNodes(rectangle37)
    rectangle38= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle38)
    @addAnimationNodes(rectangle38)
    rectangle39= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle39)
    @addAnimationNodes(rectangle39)
    rectangle40= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle32.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle40)
    @addAnimationNodes(rectangle40)
     
    rectangle41= new Rectangle(0x00fff,0,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle41)
    @addAnimationNodes(rectangle41)
    rectangle42= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle42)
    @addAnimationNodes(rectangle42)
    rectangle43= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle43)
    @addAnimationNodes(rectangle43)
    rectangle44= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle44)
    @addAnimationNodes(rectangle44)
    rectangle45= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle45)
    @addAnimationNodes(rectangle45)
    rectangle46= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle46)
    @addAnimationNodes(rectangle46)
    rectangle47= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle47)
    @addAnimationNodes(rectangle47)
    rectangle48= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle39.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle48)
    @addAnimationNodes(rectangle48)

    rectangle49= new Rectangle(0x00fff,0,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle49)
    @addAnimationNodes(rectangle49)
    rectangle50= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle50)
    @addAnimationNodes(rectangle50)
    rectangle51= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle51)
    @addAnimationNodes(rectangle51)
    rectangle52= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle52)
    @addAnimationNodes(rectangle52)
    rectangle53= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle53)
    @addAnimationNodes(rectangle53)
    rectangle54= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle54)
    @addAnimationNodes(rectangle54)
    rectangle55= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle55)
    @addAnimationNodes(rectangle55)
    rectangle56= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle45.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle56)
    @addAnimationNodes(rectangle56)
    

    rectangle57= new Rectangle(0x00fff,0,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle57)
    @addAnimationNodes(rectangle57)
    rectangle58= new Rectangle(0x000fff,rectangle1.x+rectangle1.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle58)
    @addAnimationNodes(rectangle58)
    rectangle59= new Rectangle(0x000fff,rectangle2.x+rectangle2.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle59)
    @addAnimationNodes(rectangle59)
    rectangle60= new Rectangle(0x000fff,rectangle3.x+rectangle3.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle60)
    @addAnimationNodes(rectangle60)
    rectangle61= new Rectangle(0x000fff,rectangle4.x+rectangle4.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle61)
    @addAnimationNodes(rectangle61)
    rectangle62= new Rectangle(0x000fff,rectangle5.x+rectangle5.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle62)
    @addAnimationNodes(rectangle62)
    rectangle63= new Rectangle(0x000fff,rectangle6.x+rectangle6.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle63)
    @addAnimationNodes(rectangle63)
    rectangle64= new Rectangle(0x000fff,rectangle7.x+rectangle7.w/2,rectangle56.y-window.innerHeight/8*-1/2,window.innerWidth/8,window.window.innerHeight/8)
    @stage.addChild(rectangle64)
    @addAnimationNodes(rectangle64)
    

  addAnimationNodes:(child)=>
    @animationNodes.push child
    null

  animate:=>
    @ticker.add ()=>
      for n in @animationNodes
        n.animate?()

    null

module.exports = App
